name: verify-tests

on:
  push:
    branches: [ dev/verify-tests ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dawidd6/action-rust-toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
